/-
Frozen statement of Lemma 5.1 of Bou-Rabee--Peres, *Once-reinforced random walk
on `ℤ^d` has range exponent at least `d/(d+1)`*, Section 5, Lemma
(An exponential-moment bound), label `lem:exp`, `orrw.tex:872-896`:

  "Let `d ≥ 1` and `β ≥ 1`, and let `(F_n)` be the filtration generated by
   once-reinforced random walk on `ℤ^d` with reinforcement `β`.  Let `Φ` and
   `Γ` be adapted processes with `Φ_0 = Γ_0 = 0`, and let `ζ` be a stopping
   time for this filtration.  Suppose that `(n∧ζ + Φ_{n∧ζ} - Γ_{n∧ζ})` is a
   supermartingale.  Suppose that `p`, `q` and `b` are finite constants with
     `0 ≤ Φ_{n∧ζ} ≤ p`,  `0 ≤ Γ_{(n+1)∧ζ} - Γ_{n∧ζ} ≤ q`,  `Γ_{n∧ζ} ≤ b`
   for every integer `n ≥ 0`, and let `θ := [4(1+p+q)]^{-1}`.  Then for every
   integer `N ≥ 0`,
     `E_β e^{θ(N∧ζ)/2} ≤ e^{2θb}`, and hence
     `P_β{N∧ζ ≥ 4b+s} ≤ e^{-θs/2}` for every `s ≥ 0`."

Modelling decisions.

* Ruling F-601 (the ORRW filtration).  Both the paper and the Lean statement
  use the ORRW law and its natural filtration.  Under R-001 a history of length
  `m` is a word `Fin m → Dir d`, with the step rule of `ORRW/Basic.lean`.
  The processes Phi and Gamma and the stopped time remain abstract.  At `prop:tail`
  they are the stopped versions of `ORRW.Phi`, `ORRW.Gamma` and `ORRW.sigma`.
  The author approved specializing the paper to this law and the finite-horizon
  conclusions on 2026-09-05; the frozen Lean statement is unchanged.
  Mathlib's `Supermartingale` is represented by its one-step drift inequality
  (ruling F-501).

* Ruling F-602 (adaptedness is carried by the types).  An adapted process is a
  family `Φ : ∀ m : ℕ, (Fin m → Dir d) → ℝ`: the value at time `m` is a function
  of the history of length `m`, which is what `F_m`-measurability says.  No
  measurability hypothesis is needed or can be dropped.

* Ruling F-603 (the processes are the stopped processes).  Every hypothesis of
  the paper is stated for `Φ_{n∧ζ}` and `Γ_{n∧ζ}`, so `Φ` and `Γ` below are the
  stopped processes.  The paper assumes the stopped supermartingale property,
  whose one-step form is
  `E[Φ_{(n+1)∧ζ} - δ_n | G_n] ≤ Φ_{n∧ζ} - 1_{n<ζ}` (`orrw.tex`), which is `hdrift`.  It is
  the drift inequality `eq:drift` of `lem:martingale` in the same explicit
  weighted-average form as `ORRW.Frozen.supermartingale_drift` (ruling F-502),
  with the indicator `1_{n<ζ}` on the left.

* Ruling F-604 (`ζ` is recorded through `ζ ∧ m`).  `ζ m v` represents the
  paper's `ζ ∧ m`, a function of the history of length `m`.  A stopping time
  satisfies `hζ0`, `hχ` and `hζ` with `χ m v = 1_{m<ζ}`, because
  `(m+1)∧ζ = m∧ζ + 1_{m<ζ}` and this indicator is known at time `m`.
  Lean only needs these identities and also permits other processes with
  predictable increments in `{0,1}`.  Every stopping time in the printed
  lemma satisfies the required hypotheses.

* Ruling F-605 (the conclusions are at a finite horizon).  Both the paper and
  Lean assert the exponential-moment and tail bounds for `ζ ∧ N` at every
  horizon `N`.  No infinite-horizon exponential moment is asserted.  At
  `prop:tail`, choosing a horizon beyond the tail threshold gives the required
  event bound.

* Ruling F-606 (`p`, `q`, `b`, `θ` are bound as in the paper).  They are
  parameters of the lemma, bound before the processes are constrained by them.
  No positivity is assumed: `p ≥ 0`, `q ≥ 0` and `b ≥ 0` follow from `hPhi`,
  `hδ` and `hGam` at `m = 0`, so `θ > 0`.
-/
import ORRW.Potential
import ORRW.Support.TimeCharge

open ORRW Finset

/- A truncated stopping time has increments in `{0,1}`, giving `hχ`.
The proof only needs `hdrift` to bound `χ` through `q` and `p`, so it never
appeals to `hχ`.  The unused binder is retained in the frozen statement. -/
set_option linter.unusedVariables false

-- FROZEN-STATEMENT-BEGIN
theorem ORRW.Frozen.time_versus_charge {d : ℕ} (hd : 1 ≤ d) {β : ℝ} (hβ : 1 ≤ β)
    (Φ Γ : ∀ m : ℕ, (Fin m → Dir d) → ℝ)
    (ζ χ : ∀ m : ℕ, (Fin m → Dir d) → ℕ)
    (p q b θ : ℝ)
    (hζ0 : ∀ v : Fin 0 → Dir d, ζ 0 v = 0)
    (hχ : ∀ (m : ℕ) (v : Fin m → Dir d), χ m v ≤ 1)
    (hζ : ∀ (m : ℕ) (v : Fin m → Dir d) (a : Dir d),
        ζ (m + 1) (Fin.snoc v a) = ζ m v + χ m v)
    (hΦ0 : ∀ v : Fin 0 → Dir d, Φ 0 v = 0)
    (hΓ0 : ∀ v : Fin 0 → Dir d, Γ 0 v = 0)
    (hΦ : ∀ (m : ℕ) (v : Fin m → Dir d), 0 ≤ Φ m v ∧ Φ m v ≤ p)
    (hδ : ∀ (m : ℕ) (v : Fin m → Dir d) (a : Dir d),
        0 ≤ Γ (m + 1) (Fin.snoc v a) - Γ m v ∧ Γ (m + 1) (Fin.snoc v a) - Γ m v ≤ q)
    (hΓ : ∀ (m : ℕ) (v : Fin m → Dir d), Γ m v ≤ b)
    (hdrift : ∀ (m : ℕ) (v : Fin m → Dir d),
        (χ m v : ℝ) ≤ (∑ a : Dir d, stepWeight β v m a *
              ((Γ (m + 1) (Fin.snoc v a) - Γ m v) - (Φ (m + 1) (Fin.snoc v a) - Φ m v)))
            / mu β v m)
    (hθ : θ = 1 / (4 * (1 + p + q))) :
    (∀ N : ℕ, expect N β (fun w => Real.exp (θ * (ζ N w : ℝ) / 2))
        ≤ Real.exp (2 * θ * b)) ∧
      (∀ (N : ℕ) (s : ℝ), 0 ≤ s →
        prb N β (fun w => 4 * b + s ≤ (ζ N w : ℝ)) ≤ Real.exp (-(θ * s / 2)))
-- FROZEN-STATEMENT-END
:= by
  have hdpos : 0 < d := hd
  have hp0 : 0 ≤ p := by
    have h := (hΦ 0 (Fin.elim0 : Fin 0 → Dir d)).2
    rwa [hΦ0 (Fin.elim0 : Fin 0 → Dir d)] at h
  have hq0 : 0 ≤ q := by
    have h := hδ 0 (Fin.elim0 : Fin 0 → Dir d) ((⟨0, hd⟩ : Fin d), true)
    linarith [h.1, h.2]
  have hden : (0 : ℝ) < 4 * (1 + p + q) := by positivity
  have hθpos : 0 < θ := by rw [hθ]; exact div_pos one_pos hden
  have hθval : θ * (4 * (1 + p + q)) = 1 := by
    rw [hθ, one_div, inv_mul_cancel₀ (ne_of_gt hden)]
  have hθp : θ * p ≤ 1 / 4 := by
    nlinarith [hθval, hθpos, mul_nonneg hθpos.le hq0]
  have hθq : θ * q ≤ 1 / 4 := by
    nlinarith [hθval, hθpos, mul_nonneg hθpos.le hp0]
  have hmgf : ∀ N : ℕ, expect N β (fun w => Real.exp (θ * (ζ N w : ℝ) / 2))
      ≤ Real.exp (2 * θ * b) := fun N =>
    ORRW.timeCharge_mgf hdpos hβ Φ Γ ζ χ p q b θ hθpos hθp hθq hζ0 hΦ0 hΓ0 hζ hΦ hδ hΓ hdrift N
  refine ⟨hmgf, ?_⟩
  intro N s hs
  have hmk := ORRW.prb_le_exp_of_expect_exp (N := N) hdpos hβ
      (fun w => θ * (ζ N w : ℝ) / 2) (θ * (4 * b + s) / 2) (2 * θ * b) (hmgf N)
      (fun w => 4 * b + s ≤ (ζ N w : ℝ))
      (fun w hw => by nlinarith [mul_le_mul_of_nonneg_left hw hθpos.le])
  have heq : 2 * θ * b - θ * (4 * b + s) / 2 = -(θ * s / 2) := by ring
  rwa [heq] at hmk
