"""Produce the Lean certificate: a machine-checked record of what is proved.

The certificate is generated only after the build, axiom audit, source hashes,
and paper-label checks succeed. Mathematical correspondence remains a separate
review described in VERIFICATION.md.

    python3 tools/certificate.py            # write CERTIFICATE.md
    python3 tools/certificate.py --check    # verify the file on disk is current
"""

from __future__ import annotations

import hashlib
import json
from axiom_audit import audit
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("certificate.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"
OUT = ROOT / "CERTIFICATE.md"
ELAN = str(Path.home() / ".elan" / "bin")

# The three axioms of Lean's own logic.  Anything else in a closure -- above all
# `sorryAx` -- means the statement is not proved.
CLASSICAL = {"propext", "Classical.choice", "Quot.sound"}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    import os
    env = {**os.environ, "PATH": ELAN + ":" + os.environ.get("PATH", "")}
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, env=env, **kw)


def axiom_lines(exports: list[str]) -> dict[str, str]:
    """Ask Lean for each export's axiom closure, in one elaboration."""
    imports = sorted({f"import {m}" for m in ("ORRW.Basic",)} |
                     {f"import {p}" for p in module_names()})
    src = "\n".join(imports) + "\n" + "\n".join(f"#print axioms {e}" for e in exports) + "\n"
    probe = ROOT / "scratch" / "_certificate_probe.lean"
    probe.parent.mkdir(exist_ok=True)
    probe.write_text(src, encoding="utf-8")
    try:
        r = run(["lake", "env", "lean", str(probe)], timeout=3600)
    finally:
        probe.unlink(missing_ok=True)
    return audit(r, exports)


def module_names() -> list[str]:
    names = []
    for f in sorted((ROOT / "ORRW").rglob("*.lean")):
        names.append(str(f.relative_to(ROOT).with_suffix("")).replace("/", "."))
    return names


def frozen_hash(node: dict) -> str:
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    b = text[text.index("-- FROZEN-STATEMENT-BEGIN") + len("-- FROZEN-STATEMENT-BEGIN"):
             text.index("-- FROZEN-STATEMENT-END")]
    if b.startswith("\n"):
        b = b[1:]
    return hashlib.sha256(b.encode("utf-8")).hexdigest()


def build() -> str:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    nodes = manifest["nodes"]
    exports = [n["export"] for n in nodes]

    for name in ("check_manifest", "check_coverage", "paper_anchors", "paper_citations", "sync_docs"):
        checked = run([sys.executable, f"tools/{name}.py"], timeout=120)
        if checked.returncode:
            raise ValueError(f"{name} failed:\n{checked.stdout}\n{checked.stderr}")
    for node in nodes:
        if node["state"] not in {"SEALED", "PROVED"}:
            raise ValueError(f"unproved manifest state: {node['id']}")
        if frozen_hash(node) != node["frozen_sha256"]:
            raise ValueError(f"statement hash mismatch: {node['id']}")
    r = run(["lake", "build", "ORRW"], timeout=7200)
    if r.returncode:
        raise ValueError(f"Lean build failed:\n{r.stdout}\n{r.stderr}")
    warnings = [l for l in (r.stdout + r.stderr).splitlines() if l.startswith("warning:")]
    if warnings:
        raise ValueError("Build warnings:\n" + "\n".join(warnings))

    ax = axiom_lines(exports)
    toolchain = (ROOT / "lean-toolchain").read_text().strip()
    packages = json.loads((ROOT / "lake-manifest.json").read_text())["packages"]
    ml = next(p["rev"] for p in packages if p["name"] == "mathlib")
    paper = ROOT / "paper" / "orrw.tex"
    paper_sha = hashlib.sha256(paper.read_bytes()).hexdigest()
    sources = sorted((ROOT / "ORRW").rglob("*.lean"))
    sources += [ROOT / name for name in ("ORRW.lean", "lakefile.lean", "lake-manifest.json", "lean-toolchain")]
    source_hash = hashlib.sha256()
    for path in sorted(sources):
        source_hash.update(str(path.relative_to(ROOT)).encode() + b"\0")
        source_hash.update(path.read_bytes() + b"\0")

    lines: list[str] = []
    A = lines.append
    A("# Lean certificate")
    A("")
    A("*Once-reinforced random walk on `ℤ^d` has range exponent at least `d/(d+1)`*,")
    A("Bou-Rabee–Peres.  This file records what a machine has checked, and how to")
    A("check it again.  It is generated by `python3 tools/certificate.py`; do not")
    A("edit it by hand.")
    A("")
    A("## What is claimed")
    A("")
    A("Lean checked the declarations listed below and their transitive axiom dependencies.")
    A("The source and statement hashes, paper labels, and generated documentation also passed")
    A("their checks. These checks do not prove equivalence between LaTeX and Lean statements;")
    A("see [VERIFICATION.md](VERIFICATION.md) for the correspondence and its limits.")
    A("")
    A("## Environment")
    A("")
    A("| | |")
    A("|---|---|")
    A(f"| Lean toolchain | `{toolchain}` |")
    A(f"| Mathlib revision | `{ml}` |")
    A(f"| Paper (`paper/orrw.tex`) SHA-256 | `{paper_sha}` |")
    A(f"| Lean sources and build configuration SHA-256 | `{source_hash.hexdigest()}` |")
    A("| Build | succeeded |")
    A(f"| Build warnings | {len(warnings)} |")
    A(f"| Generated | {date.today().isoformat()} |")
    A("")
    A("## Reproducing it")
    A("")
    A("```")
    A("elan toolchain install $(cat lean-toolchain)")
    A("lake exe cache get      # optional: prebuilt Mathlib")
    A("lake build ORRW")
    A("python3 tools/check_manifest.py     # frozen statements match their hashes")
    A("python3 tools/check_axioms.py       # complete output; only the three permitted axioms")
    A("python3 tools/check_warnings.py     # the build emits no unauthorized warning")
    A("python3 tools/check_coverage.py     # every paper theorem label is represented")
    A("python3 tools/certificate.py --check")
    A("```")
    A("")
    A("## The theorems, and what each depends on")
    A("")
    A("`#print axioms` reports the full transitive axiom closure of a proof.  A")
    A("closure of exactly `propext, Classical.choice, Quot.sound` is classical")
    A("mathematics and nothing more; those three are Lean's own, not ours.")
    A("`sorryAx` in a closure would mean the statement is not proved.  It appears")
    A("nowhere below.")
    A("")
    A("| # | node | Lean name | paper | axioms |")
    A("|---|---|---|---|---|")
    clean = 0
    for i, n in enumerate(nodes, 1):
        e = n["export"]
        got = {a.strip() for a in ax[e].split(",") if a.strip()}
        extra = got - CLASSICAL
        verdict = "classical only" if not extra else "**" + ", ".join(sorted(extra)) + "**"
        if not extra:
            clean += 1
        src = n["source"]
        m = re.search(r"label ([A-Za-z][A-Za-z0-9:_-]*)", src)
        paper_cell = f"`{m.group(1)}`" if m else "—"
        A(f"| {i} | `{n['id']}` | `{e}` | {paper_cell} | {verdict} |")
    A("")
    A(f"{clean} of {len(nodes)} nodes depend on nothing beyond the three classical")
    A("axioms. Every node has a checked state (`SEALED` or `PROVED`) in the manifest.")
    A("")
    A("## Frozen statements")
    A("")
    A("The bytes of each statement are pinned, so a statement cannot be weakened")
    A("after the fact without the hash changing.  `tools/check_manifest.py`")
    A("verifies these; the recipe is in `CORRESPONDENCE.md`.")
    A("")
    A("| node | SHA-256 of the frozen statement |")
    A("|---|---|")
    for n in nodes:
        h = frozen_hash(n)
        flag = "" if h == n["frozen_sha256"] else "  ← MISMATCH"
        A(f"| `{n['id']}` | `{h}`{flag} |")
    A("")
    A("## What is not claimed")
    A("")
    A("- The paper's open questions (Section 9) are questions; nothing there is")
    A("  formalized, and nothing here bears on them.")
    A("- `ORRW.Reff` is *defined* by the Schur identity, so the electrical-network")
    A("  reading of `eq:schur` is a definition here, not a theorem (ruling L-002).")
    A("- The figures, the numerical simulations and the survey in Section 1.3 are")
    A("  outside the formalization.")
    A("")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        text = build()
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        print(f"certificate: FAIL: {error}", file=sys.stderr)
        return 1
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print("certificate: CERTIFICATE.md is missing", file=sys.stderr)
            return 1
        cur = OUT.read_text(encoding="utf-8")
        # the generation date is allowed to differ
        strip = lambda s: re.sub(r"\| Generated \| .* \|", "", s)
        if strip(cur) != strip(text):
            print("certificate: CERTIFICATE.md is out of date; regenerate it",
                  file=sys.stderr)
            return 1
        print("certificate: OK (CERTIFICATE.md matches the checked state)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"certificate: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
