"""Regenerate the paper and manifest tables in README.md and CORRESPONDENCE.md.

Both documents restate what `ledger/manifest.yaml` already records: how many
nodes exist, what state each is in, and where in the paper each one comes from.
Restated facts go stale.  Everything between a BEGIN/END marker pair below is
generated from the manifest, so the prose in those files never disagrees with
the checker again.

    python3 tools/sync_docs.py            # check, exit 1 if a block is stale
    python3 tools/sync_docs.py --write    # regenerate the blocks in place
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("sync_docs.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"

SURFACE_BEGIN = "<!-- FROZEN-SURFACE-BEGIN (generated by tools/sync_docs.py) -->"
SURFACE_END = "<!-- FROZEN-SURFACE-END -->"
STATUS_BEGIN = "<!-- STATUS-BEGIN (generated by tools/sync_docs.py) -->"
STATUS_END = "<!-- STATUS-END -->"
MAP_BEGIN = "<!-- PAPER-MAP-BEGIN (generated by tools/sync_docs.py) -->"
MAP_END = "<!-- PAPER-MAP-END -->"

LABEL_RE = re.compile(r"label ([A-Za-z][A-Za-z0-9:_-]*)")
RANGE_RE = re.compile(r"orrw\.tex:\d+-\d+")


def lean_link(node: dict) -> str:
    """Link to the declaration itself, keeping line numbers derived data."""
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    matches = list(re.finditer(
        rf"^theorem\s+{re.escape(node['export'])}(?=\s|\{{|\()", text, re.M))
    if len(matches) != 1:
        raise LookupError(f"expected one declaration of {node['export']}")
    line = text.count("\n", 0, matches[0].start()) + 1
    return f"[{node['export']}]({node['file']}#L{line})"


def paper_cell(source: str) -> str:
    """Link a paper label or passage; retain supporting statements' roles."""
    rng = RANGE_RE.search(source)
    lab = LABEL_RE.search(source)
    if rng and lab:
        line = rng.group(0).split(":")[1].split("-")[0]
        return f"[{lab.group(1)}](paper/orrw.tex#L{line})"
    if rng:
        line = rng.group(0).split(":")[1].split("-")[0]
        return source.replace(rng.group(0), f"[paper passage](paper/orrw.tex#L{line})")
    if "prop:displacement" in source:
        line = paper_statements()["prop:displacement"]["line"]
        return f"[prop:displacement](paper/orrw.tex#L{line}), almost-sure clause"
    return source


def surface_table(nodes: list[dict]) -> str:
    rows = ["| id | Lean | paper | state |", "|---|---|---|---|"]
    for n in nodes:
        rows.append(
            f"| `{n['id']}` | {lean_link(n)} | {paper_cell(n['source'])} "
            f"| {n['state']} |")
    return "\n".join(rows)


def status_block(nodes: list[dict]) -> str:
    counts = Counter(n["state"] for n in nodes)
    parts = ", ".join(f"{counts[s]} `{s}`" for s in sorted(counts))
    draft = [n["id"] for n in nodes if n["state"] == "DRAFT_SORRY"]
    # State what is actually true.  Claiming a clean axiom closure while a
    # `DRAFT_SORRY` node exists is exactly the drift these blocks exist to stop.
    if draft:
        which = ", ".join(f"`{i}`" for i in draft)
        body = (
            f"The {len(nodes) - len(draft)} sealed nodes are machine-checked and no\n"
            f"sealed node's axiom closure contains `sorryAx`.  Still open: {which},\n"
            f"whose statement is frozen and whose proof is a registered `sorry`.")
    else:
        body = (
            "Every node's proof is machine-checked and its axiom closure contains\n"
            "no `sorryAx`.")
    return (
        f"Status: **{len(nodes)} frozen nodes — {parts}.**  {body}  Run\n"
        f"`python3 tools/check_axioms.py` to confirm.  Counts here are generated\n"
        f"from `ledger/manifest.yaml` by `python3 tools/sync_docs.py`; do not\n"
        f"edit them by hand and do not trust a count in prose that the checkers\n"
        f"have not confirmed.")


def paper_statements() -> dict[str, dict]:
    """Read titles, locations and the counters used by this manuscript."""
    paper = (ROOT / "paper" / "orrw.tex").read_text(encoding="utf-8")
    # Preserve newlines, so comments cannot change source links or counters.
    paper = re.sub(r"(?<!\\)%[^\n]*", "", paper)
    env = (r"\\begin\{(theorem|lemma|proposition|corollary|equation)\}"
           r"(?:\[([^\]]*)\])?\s*\\label\{([^}]+)\}")
    out, sec, seq, eq = {}, 0, 0, 0
    for m in re.finditer(r"\\section\{|" + env, paper):
        if m.group(0).startswith("\\section"):
            sec += 1
            seq = 0
        else:
            kind, title, label = m.groups()
            if label in out:
                raise LookupError(f"duplicate paper label {label}")
            if kind == "equation":
                eq += 1
                number = str(eq)
            else:
                seq += 1
                number = f"{sec}.{seq}"
            out[label] = dict(kind=kind, number=number, title=title or "",
                              line=paper.count("\n", 0, m.start()) + 1)
    expected = len(re.findall(
        r"\\begin\{(?:theorem|lemma|proposition|corollary|equation)\}", paper))
    if len(out) != expected:
        raise LookupError("a numbered paper environment has no readable label")
    return out


NOTES = {
    "lem-schur": "Effective resistance is defined by the inverse diagonal; "
                 "the electrical interpretation is not separately proved.",
    "lem-martingale": "The supermartingale property is expressed as its "
                      "equivalent one-step conditional drift inequality.",
    "prop-charge": "Proved for every finite direction history, which implies "
                   "the paper's almost-sure assertion.",
    "lem-exp": "Both formulations give bounds at every finite horizon under "
               "the ORRW law. Lean also allows predictable 0/1 increments "
               "beyond those arising from a stopped clock.",
    "prop-displacement": "Expected displacement and exit-time bounds; "
                         "the almost-sure clause has its own entry.",
    "ae-range": "Lean proves an eventual lower bound, which implies the "
                "printed liminf bound.",
    "ae-displacement": "The almost-sure clause. Lean proves an eventual lower "
                       "bound, which implies the printed liminf bound.",
    "thm-occupation": "Occupation bounds for a time interval, including "
                      "the dimension-specific estimates.",
    "thm-occupation-cesaro": "The time-averaged probability bound in the "
                             "display labelled `eq:cesaro`.",
    "thm-occupation-measure": "Uniformity in the site is expressed by a "
                              "universal quantifier inside the constant's scope.",
}

SUPPORT_ROLES = {
    "guard-total-weight-pos": "The sum of incident edge weights is positive.",
    "guard-prob-pmf": "The probabilities of all finite direction histories sum to one.",
    "guard-one-step-witness": "After one step in dimension two, the expected range is two.",
    "bridge-path-measure": "The infinite-path law has the prescribed finite-history marginals.",
}


def paper_map(nodes: list[dict]) -> str:
    """Link every paper result to its Lean declarations, in paper order."""
    statements = paper_statements()
    rows = ["| Paper result and label | Lean statement | Correspondence note |",
            "|---|---|---|"]
    entries, extra, covered = [], [], set()
    for n in nodes:
        if n["id"] in SUPPORT_ROLES:
            extra.append(n)
            continue
        lab = LABEL_RE.search(n["source"])
        label = lab.group(1) if lab else {
            "ae-range": "thm:whp", "ae-displacement": "prop:displacement",
        }[n["id"]]
        s = statements[label]
        covered.add(label)
        line, title = s["line"], s["title"]
        name = f"{s['kind'].capitalize()} {s['number']}"
        if n["id"] == "ae-range":
            paper_lines = (ROOT / "paper/orrw.tex").read_text().splitlines()
            end = next(i for i in range(line, len(paper_lines))
                       if r"\end{theorem}" in paper_lines[i])
            line = next(i + 1 for i in range(end + 1, len(paper_lines))
                        if paper_lines[i].strip())
            name = "After " + name
            title = "Almost-sure range lower bound"
        elif n["id"] == "guard-edges-le-sites":
            title = "Traversed edges bounded by visited sites"
        cell = (f"[{name}](paper/orrw.tex#L{line}): {title}"
                f"<br>`{label}`")
        note = NOTES.get(n["id"], "")
        entries.append((line, f"| {cell} | {lean_link(n)} | {note} |"))
    missing = {label for label, s in statements.items()
               if s["kind"] != "equation"} - covered
    if missing:
        raise LookupError(f"paper results missing from the map: {sorted(missing)}")
    rows.extend(row for _, row in sorted(entries, key=lambda entry: entry[0]))
    if extra:
        rows.append("")
        rows.append("The following supporting statements establish properties of "
                    "the formal model and have no separately stated paper result.")
        rows.append("")
        rows.append("| Role | Lean statement |")
        rows.append("|---|---|")
        for n in extra:
            rows.append(f"| {SUPPORT_ROLES[n['id']]} | {lean_link(n)} |")
    return "\n".join(rows)


def splice(text: str, begin: str, end: str, body: str) -> str:
    i, j = text.find(begin), text.find(end)
    if i < 0 or j < 0:
        raise LookupError(f"missing marker pair {begin!r}")
    return text[:i] + begin + "\n\n" + body + "\n\n" + text[j:]


def main() -> int:
    write = "--write" in sys.argv[1:]
    nodes = (yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}).get("nodes") or []

    try:
        targets = [
            (ROOT / "CORRESPONDENCE.md", SURFACE_BEGIN, SURFACE_END, surface_table(nodes)),
            (ROOT / "README.md", STATUS_BEGIN, STATUS_END, status_block(nodes)),
            (ROOT / "README.md", MAP_BEGIN, MAP_END, paper_map(nodes)),
        ]
    except (LookupError, KeyError) as exc:
        print(f"sync_docs: {exc}", file=sys.stderr)
        return 2

    original, updated = {}, {}
    for path, begin, end, body in targets:
        if path not in original:
            original[path] = path.read_text(encoding="utf-8")
        text = updated.get(path, original[path])
        try:
            want = splice(text, begin, end, body)
        except LookupError as exc:
            print(f"sync_docs: {path.name}: {exc}", file=sys.stderr)
            return 2
        updated[path] = want

    stale = [(path, want) for path, want in updated.items()
             if want != original[path]]

    if not stale:
        print(f"sync_docs: OK ({len(nodes)} nodes; README.md and "
              f"CORRESPONDENCE.md agree with the manifest)")
        return 0

    for path, want in stale:
        print(f"  stale: {path.relative_to(ROOT)}")
        if write:
            path.write_text(want, encoding="utf-8")

    if not write:
        print("\nsync_docs: rerun with --write to regenerate", file=sys.stderr)
        return 1
    print(f"\nsync_docs: regenerated {len(stale)} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
